### PR TITLE
Fix path-alias in monorepo

### PR DESCRIPTION
**Pull request by arjunyel**
I needed to make this change to make it work in a NX monorepo.

/ - tsconfig.base.json with rootDir: '.' and baseDir: '.'

apps/cool-backend - tsconfig.json extends tsconfig.base.json

libs/cool-library - accessible via typescript path from tsconfig.base.json

Before this change, the cool-backend wasnt able to import from cool-library because the tsconfig was getting baseDir: '.' and rootDir: '.' from tsconfig.base.json. This was generating the incorrect path for the libary, it was looking for apps/cool-backend/libs/cool-library instead of libs/cool-library.

I take the relative path to the extending tsconfig and add that relative path to all paths found in the tsconfig.

### CODE REVIEW

**Comment by sleep-written** [comment]
Hi, I need to reproduce your escenario to test the package prior to merge the pull request. I only need a simple app with NX and a few modules. Put on every package a few functions (with a simple console.log() or whatever you want), using path alias.

With this i can check if your change doesn't broke the single package applicacion execution, and if this works in more monorepo escenarios, I will can launch an update with an ifficial monorepo support.

**Comment by arjunyel** [comment]
@sleep-written added nx monorepo example 😄

**Comment by sleep-written** [comment]
I'm testing your example project, and making these tests:
## `/examples/path alias`:
- [x] __ts-node:__
  - [x] Works with `./start.sh ./src/index.ts`.
  - [x] Works with `./start.sh ./src/index.ts` (when `"rootDir": "."`).
- [x] __tsc:__
  - [x] Works with `./start.sh ./dist/index.js`.
  - [x] Works with `./start.sh ./dist/src/index.js` (when `"rootDir": "."`).
- [x] __swc:__ 
  - [x] Works with `./start.sh ./dist/index.js`.
  - [x] Works with `./start.sh ./dist/src/index.js` (when `"rootDir": "."`).

## `/examples/path-alias-monorepo`:
- [x] Works with `npx nx start monorepo-app`).
- [x] Works with `./start.sh ./src/index.ts` (cwd is `./apps/monorepo-app`).
- [ ] Works with the transpiled project(?).

My question is: __How can I transpile your project?__
Using `npx tsc` in your example project folder doesn't generate any transpiled code. And I don't see any script inside of any `package.json` to transpile your project. To merge your pull request I must check that your transpiled projects works too.

**Comment by arjunyel** [comment]
Added transpile example

**Comment by sleep-written** [comment]
## About testing the functionality
I checked if your changes works in the targeted escenarios, so here's the result:

### `/examples/path alias`:
- [x] __ts-node:__
  - [x] Works with `./start.sh ./src/index.ts`.
  - [x] Works with `./start.sh ./src/index.ts` (when `"rootDir": "."`).
  - [x] Works with `./start.sh ./src/index.ts` (when `"rootDir": "."` and `"baseUrl": "."`).
- [x] __tsc:__
  - [x] Works with `./start.sh ./dist/index.js`.
  - [x] Works with `./start.sh ./dist/src/index.js` (when `"rootDir": "."`).
  - [x] Works with `./start.sh ./dist/src/index.js` (when `"rootDir": "."` and `"baseUrl": "."`).
- [x] __swc:__ 
  - [x] Works with `node ./dist/index.js`.
  - [x] Works with `node ./dist/src/index.js` (when `"baseUrl": "."`).

### `/examples/path-alias-monorepo`:
- [x] Works with `npx nx start monorepo-app`).
- [x] Works with `node --loader @bleed-believer/path-alias/esm ./src/main.mts` (cwd is `./apps/monorepo-app`).
- [x] Works with `node ./dist/apps/monorepo-app/src/main.mjs` (transpiled, using [tsc-alias](https://www.npmjs.com/package/tsc-alias) after building).

## Suggestions for your monorepo
As a protip, in your `./apps/monorepo-app/project.json`, in your commands:
- You don't need to use the full path of the loader, instead just put the library path like this:
  ```json
  "node --no-warnings --loader @bleed-believer/path-alias/esm ./src/main.mts"
  ```
- As you are using [tsc-alias](https://www.npmjs.com/package/tsc-alias), you don't need to use `@bleed-believer/path-alias` to execute your transpiled project:
  ```json
  "node ../../dist/apps/monorepo-app/src/main.mjs"
  ```

So your `./apps/monorepo-app/project.json` should be like this:
```json
{
  "name": "monorepo-app",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/monorepo-app",
  "projectType": "application",
  "tags": [],
  "targets": {
    "start": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "apps/monorepo-app",
        "commands": [
          "node --no-warnings --loader @bleed-believer/path-alias/esm ./src/main.mts"
        ]
      }
    },
    "build": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "apps/monorepo-app",
        "commands": [
          "tsc",
          "tsc-alias",
          "node ../../dist/apps/monorepo-app/src/main.mjs"
        ],
        "parallel": false
      }
    }
  }
}
```

## Final thoughts
Thanks for working in this PR! your work will improve the funcionality of this library. I'll add these suggestions in the review.

**Review by sleep-written — APPROVED** [review]

**Comment by sleep-written** [comment]
Hi @arjunyel, your PR is done and the package has been updated in __npm__. If you want to add this in your project, just install the latest version:
```sh
npm i --save @bleed-believer/path-alias
```

**Comment by arjunyel** [comment]
@sleep-written thank you for creating the library and your help friend!

**Pull request merged**
